-- Seed parties
INSERT INTO parties (id, name, summary, created_at)
VALUES (1, 'Ahora Nación', 'Ahora Nación (AN) es un partido político peruano de alcance nacional que se define ideológicamente como una coalición de centro izquierda. Su principio articulador central es la idea de que el Perú es una nación en proceso de formación, y que completar esa construcción nacional constituye su principal tarea histórica. En ese marco, promueve una descentralización profunda del poder hacia las regiones como mecanismo de desarrollo productivo e industrialización nacional, y propugna la igualdad de derechos para todos los ciudadanos sin distinción de raza, género, condición social ni económica.

El partido se concibe a sí mismo también como una escuela de formación política ciudadana, orientada a fomentar la participación ética, democrática y responsable de la ciudadanía. Sus valores institucionales incluyen el respeto, la lealtad, la solidaridad, la tolerancia, la honestidad, la transparencia y la integridad, con un énfasis particular en el rechazo a la corrupción tanto en la vida pública como privada de sus militantes.

En términos programáticos, el partido busca consolidar un Estado democrático, soberano y descentralizado, libre de corrupción, con instituciones sólidas, separación de poderes y alternancia en el gobierno. Propone garantizar servicios públicos de calidad en salud y educación, fortalecer el sistema de justicia sin privilegios, y asegurar la participación de la sociedad civil organizada en todos los niveles de gobierno. Su visión económica apunta al fomento de un empresariado nacional innovador que impulse la ciencia, la tecnología y la investigación, en articulación con la defensa de los derechos de los trabajadores urbanos y rurales.',
        '2026-03-22 06:15:37.209667+00'::timestamptz),
       (2, 'Alianza para el Progreso', 'Alianza para el Progreso (APP) es un partido político peruano fundado en la ciudad de Trujillo, de inspiración humanista, democrática, social y descentralista. Sus principios fundamentales incluyen la participación ciudadana libre y competitiva, la igualdad sin discriminación, la independencia frente a poderes fácticos nacionales y transnacionales, la transparencia financiera, la integración política y social, y la autonomía institucional orientada por sus propios principios y objetivos.

Ideológicamente, el partido se sitúa en una posición de centro, combinando valores de la democracia liberal con énfasis en la justicia social, la descentralización del poder y el desarrollo sostenible. Promueve la participación activa del Estado en la garantía de derechos y servicios básicos, al tiempo que fomenta la inversión privada y el crecimiento del sector productivo, lo que refleja una orientación pragmática que no se adscribe de manera rígida ni a la derecha ni a la izquierda del espectro político.

Entre sus principales objetivos programáticos se encuentran la defensa y fortalecimiento del sistema democrático, la representación de la voluntad ciudadana, la vigencia de los derechos humanos y las libertades fundamentales, y la promoción de la gobernabilidad mediante el consenso entre organizaciones políticas y la sociedad. El partido se propone combatir la pobreza extrema, generar empleo digno, fomentar la inversión privada y las pequeñas y medianas empresas, impulsar la descentralización y regionalización, y promover el desarrollo científico, tecnológico, educativo y cultural. Asimismo, otorga especial atención a grupos vulnerables como menores de edad, mujeres, adultos mayores, personas con discapacidad, y comunidades campesinas y nativas, buscando su incorporación plena en igualdad de oportunidades. La transparencia en el manejo de los recursos públicos y la formación cívica y política de la ciudadanía constituyen también ejes centrales de su acción partidaria.',
        '2026-03-22 06:15:47.892762+00'::timestamptz),
       (3, 'Avanza Pais - Partido de Integracion Social', 'Avanza País - Partido de Integración Social es una organización política peruana de alcance nacional, fundada simbólicamente en Cachicadán, provincia de Santiago de Chuco, con domicilio funcional en Lima. Su denominación refleja su propósito central: la integración social como eje articulador de su proyecto político.

En cuanto a sus principios y valores, el partido se sustenta en la democracia participativa, la libertad individual, la solidaridad y reciprocidad inspiradas en prácticas ancestrales andinas como el Ayni y la Minca, la ética social basada en los principios morales incaicos del Ama Sua, Ama Quella y Ama Llulla, la confianza como cohesión colectiva, y la creatividad empresarial como motor del desarrollo humano. Otorga especial relevancia a la herencia cultural prehispánica y al respeto por el medio ambiente, la biodiversidad y los recursos naturales.

Desde el punto de vista ideológico, el partido se ubica en la corriente socialdemócrata, adoptando sus bases doctrinarias con flexibilidad y sin dogmatismos. Se declara defensor del sistema democrático, los derechos humanos y el Estado de derecho, y se posiciona como una alternativa al neoliberalismo desde una perspectiva de integración social con identidad nacional. Promueve la economía social de mercado y el respeto a la propiedad privada.

Sus principales objetivos programáticos se articulan en torno a tres grandes proyectos: la integración social del país mediante revoluciones en los ámbitos educativo, productivo, vial-ferroviario, turístico y ético-moral; el impulso de un modelo de desarrollo alternativo al neoliberalismo que combata la discriminación, la desocupación y la exclusión; y la integración latinoamericana a través de una gran red ferroviaria continental. En términos más específicos, el partido busca fortalecer la descentralización, combatir la corrupción y la inseguridad ciudadana, mejorar los servicios de salud y educación, promover la investigación científica y tecnológica, proteger a la familia, la niñez, la mujer y los adultos mayores, profesionalizar las fuerzas del orden y las Fuerzas Armadas, fomentar el empleo digno bajo criterios de meritocracia, impulsar la agricultura, ganadería, pesca y una minería ambientalmente responsable, y promover una cultura cívica y democrática entre la ciudadanía.',
        '2026-03-22 06:15:59.414997+00'::timestamptz),
       (4, 'Fe en el Perú', 'Fe en el Perú es un partido político peruano de orientación democrática, descentralista e innovadora, que se define como una organización comprometida con el bien común, el fortalecimiento del sistema representativo y la renovación de la cultura política en el país. Sus principios fundacionales incluyen la fe como valor inspirador de la acción ciudadana, el respeto a la diversidad de opiniones, la honestidad y transparencia, la igualdad ante la ley con pleno respeto a los derechos humanos, el sentido social, la creatividad e innovación, la vocación de servicio y la docencia cívica como herramienta de empoderamiento ciudadano.

En términos ideológicos, el partido se sitúa en una posición de centro democrático, sin adscribirse explícitamente a una corriente de izquierda o derecha. Combina la promoción de la inversión privada y pública como motor del crecimiento económico con un énfasis en la justicia social, la solidaridad y la descentralización del poder político hacia los gobiernos locales, provinciales y regionales.

Sus principales objetivos programáticos apuntan a consolidar una democracia deliberativa y participativa, erradicar la corrupción mediante una cultura de transparencia y probidad, impulsar el empoderamiento ciudadano desde las bases comunitarias, garantizar el acceso universal a educación, salud y seguridad, y promover la formación de liderazgos locales. Asimismo, el partido busca incentivar la inversión responsable, fomentar la innovación científica y tecnológica, y desarrollar actividades de promoción cultural, deportiva y de formación laboral orientadas especialmente a los jóvenes.',
        '2026-03-22 06:16:15.05004+00'::timestamptz),
       (5, 'Fuerza Popular', 'Fuerza Popular es un partido político peruano con domicilio legal en Lima y duración indefinida. Su estatuto establece como pilares fundamentales la defensa del sistema democrático, el estado constitucional de derecho, la paz, la libertad y la vigencia de los derechos humanos reconocidos por la Constitución Política del Perú.

Desde el punto de vista ideológico, el partido no declara explícitamente en su estatuto una corriente ideológica específica, aunque su orientación general se enmarca en la defensa del orden constitucional, la institucionalidad democrática y el desarrollo sostenible del país, con referencias implícitas a valores de centro-derecha asociados al fujimorismo como movimiento político de origen.

Entre sus principales objetivos programáticos se encuentran la participación activa en procesos electorales, la representación de la voluntad ciudadana, la formación cívica y democrática de sus militantes, y la investigación de problemas socioeconómicos y políticos nacionales con miras a proponer soluciones. El partido también establece como objetivo contribuir a la gobernabilidad del país y desarrollar actividades de cooperación y proyección social.

En cuanto a su estructura interna, el estatuto regula detalladamente los derechos y deberes de los afiliados, enfatizando valores como la honestidad, la disciplina, la lealtad, la transparencia y la integridad. Otorga especial atención a la participación política de las mujeres, reconociendo explícitamente su derecho a participar en igualdad de condiciones y estableciendo mecanismos para prevenir y denunciar el acoso político de género. El régimen disciplinario interno busca garantizar el debido proceso en la investigación y sanción de conductas contrarias a las normas partidarias.',
        '2026-03-22 06:16:25.613399+00'::timestamptz),
       (6, 'Fuerza y Libertad', 'Batalla Perú es un partido político peruano de orientación democrática, descentralista y reformista, cuya identidad se ancla en la historia patriótica del país, particularmente en el legado de la independencia nacional. Sus principios centrales son la identidad histórica, social y cultural del Perú, la autonomía, independencia y soberanía nacional, la articulación e integración territorial y social, y la unidad y cohesión social.

Desde el punto de vista ideológico, el partido se posiciona en un espacio de centro reformista, combinando valores democráticos, patrióticos y de modernización del Estado, sin adscribirse de manera explícita a una corriente ideológica de izquierda o derecha tradicional. Promueve una economía inclusiva y sostenible, lo que sugiere una postura favorable a la intervención estatal en materia social sin rechazar la inversión privada.

Sus principales objetivos programáticos incluyen la construcción de una democracia auténtica y una sociedad justa, el desarrollo de una economía inclusiva y sostenible, el fortalecimiento del sistema de justicia y la seguridad ciudadana, la modernización y eficiencia del aparato estatal, el desarrollo integral de la persona, el impulso a la educación, la ciencia y la sociedad del conocimiento, y la sostenibilidad ambiental con conservación de recursos naturales. El partido declara también su compromiso con la lucha contra la corrupción, la descentralización efectiva y el acceso universal a educación, salud y seguridad como condiciones para un Perú más equitativo y próspero.',
        '2026-03-22 06:16:37.075886+00'::timestamptz),
       (7, 'Juntos por el Perú', 'Juntos por el Perú es un partido político peruano de izquierda y centroizquierda que surge como una coalición amplia que integra fuerzas progresistas, patrióticas y populares, articuladas desde la base organizativa del Partido Humanista Peruano fundado en 2001. El partido se define explícitamente como una organización pluriideológica que agrupa sectores de izquierda, centroizquierda y el movimiento popular pluricultural y multiétnico, con disposición a mantener relaciones internacionales con organizaciones afines a la centroizquierda.

Sus principios y valores centrales son la libertad, la igualdad, la equidad, la justicia, la solidaridad, la paz y el trabajo. A estos se suman el compromiso con la igualdad de oportunidades entre hombres y mujeres, la economía solidaria, la conservación del medio ambiente y el aprovechamiento sostenible de los recursos naturales, así como el reconocimiento de la interculturalidad, la tolerancia y el fomento de liderazgos democráticos en una sociedad que se concibe como plurinacional, multiétnica y pluricultural.

En términos ideológicos, el partido rechaza explícitamente las políticas neoliberales y el modelo primario exportador, a los que atribuye la profundización de la pobreza y la desigualdad en el país. Propone en su lugar la construcción de una República Humanista basada en un nuevo ordenamiento constitucional, un modelo de desarrollo alternativo, la distribución equitativa de la riqueza, la sostenibilidad ambiental y el fortalecimiento de la institucionalidad democrática participativa.

Sus principales objetivos programáticos incluyen la defensa del sistema democrático y los derechos humanos, la descentralización y regionalización del país con participación ciudadana, la lucha frontal contra la corrupción mediante políticas públicas y una cultura de transparencia, y la priorización de los sectores en situación de pobreza como fin central del Estado y la sociedad. Asimismo, busca fortalecer las instituciones democráticas y promover la participación política ciudadana sin distinciones de raza, género, credo, origen cultural ni condición socioeconómica.',
        '2026-03-22 06:16:47.851186+00'::timestamptz),
       (8, 'Libertad Popular', 'Libertad Popular es un partido político peruano fundado el 31 de diciembre de 2021, con alcance nacional y domicilio legal en la ciudad de Lima. Sus principios fundamentales giran en torno a la libertad como fin supremo del ciudadano, la democracia como forma de gobierno, el estado de derecho, la solidaridad entre peruanos y el respeto a los derechos humanos. El partido también proclama la honestidad como valor y patrón cotidiano de conducta, y promueve la igualdad ante la ley y la independencia de la justicia frente al poder político y económico.

En términos ideológicos, el partido se sitúa en una orientación de centro orientada hacia el liberalismo político y la economía social de mercado, concibiendo esta última como el principal instrumento para superar la pobreza, generar empleo digno y promover el desarrollo sostenible. Esta posición combina la defensa de libertades individuales con un reconocimiento de la educación como derecho fundamental y de la solidaridad como necesidad social.

Sus principales objetivos programáticos incluyen la promoción y defensa de la libertad y la democracia, la difusión del modelo de economía social de mercado, la garantía de igualdad ante la ley, el impulso de una justicia independiente, el fomento de la honestidad en la vida pública y el fortalecimiento de la solidaridad y reconciliación entre los peruanos. A nivel organizativo, el partido cuenta con estructuras nacionales y provinciales, así como con un Comité de Ética Nacional y Lucha contra la Corrupción, lo que refleja un énfasis formal en la transparencia y la integridad interna.',
        '2026-03-22 06:17:02.156681+00'::timestamptz),
       (9, 'Partido Aprista Peruano', 'El Partido Aprista Peruano (PAP) es un partido de izquierda democrática fundado en Lima el 20 de septiembre de 1930, bajo los principios doctrinarios establecidos por su fundador Víctor Raúl Haya de la Torre en el marco de la Alianza Popular Revolucionaria Americana (APRA). Su ideario se sustenta en cinco principios originales: la acción contra el imperialismo, la unidad política y económica de América Latina, la nacionalización progresiva de tierras e industrias, la interamericanización del Canal de Panamá y la solidaridad con los pueblos y clases oprimidas del mundo.

Ideológicamente, el partido se define como un movimiento político, económico y social de proyección peruana e indoamericana, que responde a una realidad caracterizada por el capitalismo subdesarrollado y dependiente. Defiende la democracia integral, las libertades fundamentales y el Estado de derecho, rechazando toda forma de imperialismo, totalitarismo y dictadura. Su lema programático es ''"Fe, Unión, Disciplina y Acción''", y concibe su acción política como una alianza entre obreros, campesinos, clases medias, profesionales, estudiantes, emprendedores y pequeños y medianos empresarios.

Entre sus principales objetivos programáticos se encuentran la promoción de la justicia social bajo el concepto de ''"Pan con Libertad''", el impulso al desarrollo económico con énfasis en la industrialización, la tecnificación agrícola y la defensa de la pequeña y mediana propiedad. Propugna formas empresariales cooperativas y autogestionarias, la explotación científica y tecnológica de los recursos naturales, y la elevación del nivel de vida de los sectores marginados, con el fin de erradicar la explotación del hombre por el hombre y por el Estado.

En el plano institucional, plantea la creación de un Congreso Económico Nacional que articule los intereses del Estado, el trabajo y el capital. En política exterior e integración, promueve la unidad política y económica de América Latina y el Caribe, la solución al problema de la deuda externa, la regionalización e integración nacional, y la integración andina orientada hacia la unidad indoamericana. Asimismo, defiende el patrimonio arqueológico, histórico, cultural y ecológico del país, e impulsa la adopción de avances científicos y tecnológicos al servicio del desarrollo nacional.',
        '2026-03-22 06:17:11.931273+00'::timestamptz),
       (10, 'Partido Cívico OBRAS', 'El Partido Cívico Obras es una organización política peruana fundada con el propósito de participar en los asuntos públicos del país a través de medios democráticos, dentro del marco constitucional vigente. Su orientación ideológica se inscribe en una línea humanista, democrática y social, con énfasis en la construcción de un Estado descentralizado, solidario e inclusivo que garantice la igualdad de oportunidades para todos los ciudadanos.

Entre sus principios centrales destacan la defensa de los derechos humanos, la dignidad de la persona como fin supremo del Estado y la sociedad, la preservación de las libertades fundamentales y el fortalecimiento de la cultura cívica y democrática. El partido promueve una economía social de mercado que rechaza los monopolios y oligopolios, en la que el Estado cumple un rol activo en garantizar las necesidades básicas de la población y en regular la libre iniciativa y la inversión privada.

Sus objetivos programáticos principales incluyen el acceso universal a una educación pública gratuita y de calidad, la prestación de servicios de salud universal con prioridad a los sectores más vulnerables, la erradicación de la corrupción mediante medidas como la imprescriptibilidad de delitos contra el Estado y la inhabilitación permanente de funcionarios sentenciados, así como la transparencia en las contrataciones públicas. Asimismo, promueve la descentralización política, económica y administrativa, la revisión de contratos sobre recursos naturales en defensa del interés nacional, el establecimiento de pensiones dignas para jubilados, el fomento del deporte y la cultura como herramientas de formación integral, y la regulación de los medios de comunicación para garantizar contenidos con valores cívicos y protección a los menores.',
        '2026-03-22 06:17:26.608449+00'::timestamptz),
       (11, 'Partido Democratico Somos Peru', 'Somos Perú es un partido político peruano de orientación democrática, descentralista y participativa, fundado sobre la primacía de la persona humana como fin supremo de la sociedad y del Estado. Su posición ideológica se inscribe en una democracia social y constitucional, con énfasis en la descentralización del poder, la participación ciudadana desde las bases y el respeto irrestricto a los derechos humanos y las instituciones.

Entre sus principios fundamentales se encuentran la defensa de la dignidad y los derechos fundamentales de la persona, la promoción del trabajo como medio de satisfacción de necesidades humanas, la dimensión social de la empresa privada, el rol subsidiario del Estado, la búsqueda del bien común, la institucionalidad democrática y constitucional, la defensa del patrimonio natural, arqueológico, histórico y cultural, y la promoción de la educación para el desarrollo integral de la persona y la sociedad.

El partido se organiza bajo el principio de democracia interna, según el cual la voluntad política surge de las bases hacia la dirigencia, y cada nivel organizativo —local y regional— adopta sus decisiones con autonomía, conforme al principio de subsidiariedad. Aspira a congregar a ciudadanos de distintos estratos, creencias, géneros y condiciones sociales, sin discriminación de ningún tipo.

Sus principales objetivos programáticos incluyen el fortalecimiento del Estado constitucional, democrático, descentralizado y social; la construcción de una sociedad justa, libre y solidaria; la subordinación de la economía al servicio de la persona; el desarrollo integral, armónico y sostenible basado en la descentralización; y la canalización de los intereses y necesidades de la población por encima de intereses partidarios o de grupos de poder. Participan en procesos electorales a nivel nacional, regional y local con el fin de representar la voluntad ciudadana y contribuir a la vigencia del sistema democrático en el Perú.',
        '2026-03-22 06:17:37.407342+00'::timestamptz),
       (12, 'Partido Democrático Federal', 'El Partido Democrático Federal es una organización política peruana cuya propuesta central es la transformación del sistema de gobierno unitario hacia un modelo de república federal, entendido como el mecanismo principal para superar el centralismo que, según su ideario, ha perpetuado la pobreza, la desigualdad y la exclusión regional durante siglos. Sus principios fundamentales se articulan en torno a la solidaridad, la subsidiaridad, la fraternidad, el respeto irrestricto a los derechos humanos, la soberanía nacional y el rechazo a la corrupción, el narcotráfico y toda forma de concentración abusiva del poder.

Desde el punto de vista ideológico, el partido se posiciona como federalista e integrador, con un enfoque pragmático que no se adscribe rígidamente a una corriente única, sino que toma como referencias modelos diversos como el liberalismo económico estadounidense, el desarrollismo industrial de Corea del Sur, el fondo soberano de recursos naturales de Noruega y el modelo de crecimiento chino. Esta orientación ecléctica se sintetiza en la cita atribuida a Deng Xiaoping que incluye en su estatuto, priorizando los resultados sobre la doctrina. Al mismo tiempo, reivindica la herencia histórica y cultural andina, incluyendo el legado del Tawantinsuyo y las luchas anticoloniales, como fundamento identitario del federalismo que propone.

Sus objetivos programáticos se orientan hacia la industrialización descentralizada mediante la incorporación de tecnologías de la cuarta revolución industrial en cada región federal, incluyendo inteligencia artificial, robótica, nanotecnología y biotecnología. En materia educativa, propone garantizar una educación pública de calidad en todos los niveles, con énfasis en la innovación tecnológica y la formación ciudadana. En el ámbito económico, busca promover el desarrollo de empresas con presencia global, proteger la pequeña y mediana empresa, regular el sistema financiero y transformar los recursos naturales con valor agregado. En el sector agrario, plantea dotar de infraestructura hídrica a agricultores y ganaderos de la sierra para garantizar la soberanía alimentaria. Asimismo, propone reformar el sistema de justicia mediante la elección democrática regional de fiscales y jueces, fortalecer las fuerzas de seguridad con tecnología avanzada, proteger a los sectores vulnerables mediante políticas constitucionales de salud y bienestar, garantizar la equidad de género en todos los ámbitos de la vida pública y promover la protección del medioambiente frente a la actividad contaminante.',
        '2026-03-22 06:17:50.132409+00'::timestamptz),
       (13, 'Partido Demócrata Unido Perú', 'El Partido Demócrata Unido Perú es una organización política peruana de carácter democrático que se rige por principios de igualdad, libertad, equidad, justicia social, honestidad, transparencia, responsabilidad, probidad y bien común. Su símbolo, el color verde loro, representa la esperanza, y su sede central se encuentra en Lima, con proyección nacional.

En términos ideológicos, el partido se posiciona dentro de una orientación democrática, participativa y descentralista, con énfasis en la justicia social, la identidad nacional y la protección del medio ambiente. No se adscribe explícitamente a una corriente ideológica clásica de izquierda o derecha, sino que combina elementos de democracia social, desarrollismo y humanismo cívico.

Sus principales objetivos programáticos incluyen la consolidación de la democracia participativa y el Estado de Derecho, la defensa de los derechos humanos y las libertades fundamentales, y la promoción de una educación pública gratuita, formativa, técnica y orientada a la innovación y la investigación. El partido busca impulsar la descentralización del poder, fortalecer la seguridad social en salud y pensiones, y consolidar una economía estable basada en la diversificación productiva, la industrialización de materias primas y el uso de tecnologías de la información. Asimismo, plantea combatir la desigualdad, la discriminación y los privilegios, promover la conectividad física y virtual como mecanismo de integración nacional, y desarrollar políticas de conservación ambiental y aprovechamiento responsable de la biodiversidad. Finalmente, el partido se propone contribuir a la renovación de la clase política y a la modernización de la gestión pública.',
        '2026-03-22 06:18:05.768144+00'::timestamptz),
       (14, 'Partido Demócrata Verde', 'El Partido Demócrata Verde es una organización política peruana fundada en 2021 que se adscribe a la corriente del ecologismo modernista o reformista, posicionándose fuera del espectro convencional de izquierda y derecha. Su base ideológica combina la democracia representativa, el humanismo, la ecología política y el desarrollo sostenible, tomando como referencia los principios de la red internacional Global Greens y su Carta de los Verdes Mundiales.

Entre sus valores centrales destacan el respeto al medio ambiente, la transparencia en la gestión pública, la libertad, la inclusión social, la igualdad de oportunidades y la integridad humana. El partido acepta el marco de la economía de mercado y el desarrollo capitalista, pero reconoce la existencia de límites al crecimiento económico, promoviendo prácticas productivas compatibles con la sostenibilidad ecológica y el uso eficiente de recursos naturales y energías renovables.

Sus objetivos programáticos se articulan en torno a siete principios. En materia ambiental, busca proteger la biodiversidad, fomentar energías renovables y reducir la contaminación. En el ámbito económico y tecnológico, promueve la innovación, la competitividad y el desarrollo científico con criterios de sostenibilidad. En el plano social, propugna la justicia social, la eliminación de la pobreza y la erradicación de toda forma de discriminación. En educación y salud, plantea una transformación del modelo educativo hacia el desarrollo de capacidades individuales y la integración de tecnología, así como la mejora de los servicios de salud pública. Transversalmente, el partido enfatiza la descentralización administrativa, la participación ciudadana activa y la transparencia en la gestión del Estado.',
        '2026-03-22 06:18:15.727927+00'::timestamptz),
       (15, 'Partido Frente de la Esperanza 2021', 'El Partido Frente de la Esperanza 2021 es una organización política peruana que se define como una asociación ciudadana sin fines de lucro, orientada a la participación democrática en la vida política del país. Sus principios fundamentales incluyen la dignidad de la persona humana, la democracia, la legalidad, la libertad, la igualdad, la justicia, la solidaridad, la responsabilidad, la verdad, la honestidad y el trabajo, enmarcados en el respeto a la Constitución Política y al Estado Constitucional de Derecho.

Desde el punto de vista ideológico, el partido no declara explícitamente una posición en el espectro izquierda-derecha, sino que articula su identidad en torno a valores cívicos, republicanos y democráticos, con énfasis en la transparencia, la ética pública y el rescate de valores morales y cívicos. El uso de la escoba como símbolo sugiere un discurso orientado hacia la renovación política y la lucha contra la corrupción.

Entre sus principales objetivos programáticos se encuentran la defensa del sistema democrático y la gobernabilidad, la preservación de los derechos humanos, la representación y canalización de las demandas ciudadanas, y la promoción de una cultura cívica participativa. El partido también se propone contribuir al desarrollo social, económico y cultural del país, fomentar la participación de mujeres, hombres y jóvenes en la vida política, y rechazar la demagogia y la improvisación como formas de acción política. Su estructura interna contempla mecanismos de disciplina, debido proceso y participación igualitaria de sus afiliados.',
        '2026-03-22 06:18:26.180196+00'::timestamptz),
       (16, 'Partido Morado', 'El Partido Morado es una organización política peruana de duración indefinida que orienta su acción dentro del marco constitucional y democrático del país. Sus principios fundacionales se articulan en torno a cuatro ejes: la libertad individual, entendida como la generación de condiciones equitativas para el desarrollo personal sin discriminación ni privilegios; la acción colectiva, que propugna la vida en sociedad mediante instituciones democráticas, la justicia social, la solidaridad, la descentralización y la lucha contra la corrupción; el entorno biofísico, que implica la conservación y uso racional de los recursos naturales, la protección ambiental y la transición hacia energías limpias; y la superación y trascendencia, que busca articular una visión de futuro basada en el conocimiento, la excelencia y el desarrollo del talento humano.

Desde el punto de vista ideológico, el partido se posiciona en un espacio de centro progresista o liberal progresista, combinando la defensa de las libertades individuales y la economía de mercado diversificada con un énfasis en la justicia social, la inclusión, la modernización del Estado y el respeto por el medio ambiente.

Sus principales objetivos programáticos incluyen la defensa del sistema democrático y los derechos humanos, la inversión masiva en educación, ciencia y tecnología, la provisión universal de servicios públicos de calidad, la construcción de un Estado transparente y libre de corrupción, la diversificación productiva y el apoyo al emprendimiento, la reducción de la desigualdad y la discriminación, la integración territorial mediante conectividad física y digital, y el aprovechamiento sostenible de la diversidad natural y cultural del país. El partido también se propone contribuir a la renovación de la clase política y funcionar como una organización formativa para sus militantes.',
        '2026-03-22 06:18:36.054874+00'::timestamptz),
       (17, 'Partido PRIN', 'El Partido Regionalista de Integración Nacional (PRIN) es un partido político peruano de orientación de centro con espíritu regionalista, que opera a nivel nacional con sede en Lima. Su fundamento ideológico combina el regionalismo con la integración nacional, expresado en su lema ''"El Perú, una sola región''", buscando articular las dinámicas territoriales descentralizadas con la unidad del Estado peruano.

Entre sus principios y valores fundamentales se encuentran el mantenimiento del sistema democrático, el respeto a los derechos humanos, la Constitución Política y las leyes del Perú, así como el fomento de una cultura cívica y democrática. El partido incorpora referencias a la identidad cultural andina y costeña en su simbología, utilizando elementos como la ardilla del friso de Chan Chan, el Tumi de la cultura Wari y el Gallito de las rocas, lo que refleja una valoración del patrimonio histórico y regional del país.

En términos programáticos, el PRIN busca contribuir al desarrollo nacional desde una perspectiva regionalista, promoviendo la participación política descentralizada mediante estructuras organizativas en los ámbitos regional, provincial, distrital y en el exterior. Sus áreas de acción programática abarcan campos como la educación, la salud, el bienestar social, la lucha contra la pobreza, la inclusión social, la seguridad ciudadana, la agricultura, el medio ambiente, el turismo, el desarrollo de la pequeña y mediana empresa, y los derechos humanos. El partido otorga especial atención a la participación juvenil a través de sus ramas JORE y JURE, así como a la inclusión de la mujer y poblaciones vulnerables dentro de su estructura orgánica.',
        '2026-03-22 06:18:47.735472+00'::timestamptz),
       (18, 'Partido Patriótico del Perú', 'El Partido Patriótico del Perú (PPP), fundado en 2020, se define como una organización democrática, participativa, descentralizada e independiente, con una orientación doctrinaria centrada en el patriotismo como valor fundamental. Sus principios rectores giran en torno al amor y servicio a la patria, la meritocracia, el respeto a las instituciones del Estado, la soberanía nacional, la interculturalidad, los derechos humanos, la lealtad y la coherencia entre el discurso y la acción. El partido reivindica la identidad cultural peruana, incluyendo el legado andino e inca, y promueve el respeto a la diversidad sin discriminación por raza o credo.

Desde el punto de vista ideológico, el partido combina elementos nacionalistas y estatistas con un discurso de orden institucional y eficiencia pública. Defiende un rol activo del Estado en la economía y en la prestación de servicios, sin adscribirse explícitamente a una corriente de izquierda o derecha tradicional. Su orientación es pragmática y centrada en la gestión pública por resultados, con énfasis en la soberanía frente a intereses extranjeros y en el desarrollo nacional autónomo.

Sus objetivos programáticos se articulan en cinco pilares fundamentales: educación, salud y nutrición, trabajo y producción, seguridad interna y externa, y lucha contra la corrupción. En educación, propone una reforma orientada a la calidad, la enseñanza del quechua y otros idiomas, la descentralización universitaria y la integración del deporte en la formación integral. En salud, prioriza el combate a la desnutrición infantil y el fortalecimiento del sistema sanitario público. En el ámbito económico y productivo, plantea la industrialización del país con valor agregado en las exportaciones, la creación de empresas estatales en transporte aéreo, ferroviario, marítimo y pesquero, la regulación de la adquisición de tierras por capitales extranjeros, la homologación salarial en el sector público y el impulso de la economía creativa y sostenible. El conjunto de estas propuestas refleja una visión de desarrollo nacional orientada hacia la autosuficiencia, la equidad territorial y la eficiencia institucional.',
        '2026-03-22 06:18:58.634446+00'::timestamptz),
       (19, 'Partido País para Todos', 'Partido País para Todos es una organización política peruana de alcance nacional, fundada el 25 de abril de 2023, con domicilio legal en Lima. Sus principios se articulan en torno al respeto al orden constitucional, la democracia, la transparencia, la libertad de expresión y el control de los recursos públicos. El partido adhiere a una posición ideológica de centro, orientada hacia el desarrollo económico y social dentro de un marco de economía social de mercado, con énfasis en la participación ciudadana, la justicia social, la solidaridad y el estado de derecho democrático.

Entre sus principales objetivos programáticos destacan la promoción del desarrollo social con participación democrática, la defensa de los derechos de los pueblos étnicos originarios, andinos y amazónicos, y la ampliación de infraestructura vial y de comunicaciones en zonas con escasa presencia estatal. El partido también propugna el acceso universal al agua potable como derecho humano, la preservación de la diversidad ecológica frente al cambio climático, y el fortalecimiento del sistema educativo con valores cívicos y éticos. En materia económica, impulsa la estabilidad financiera, la seguridad jurídica para los actores económicos y la innovación agrotecnológica orientada a la agricultura familiar sostenible. Asimismo, promueve la protección de la niñez y de la familia como núcleo fundamental de la sociedad, el respeto irrestricto a los derechos humanos, la independencia de poderes del Estado y el fomento de la cultura deportiva.',
        '2026-03-22 06:19:48.542633+00'::timestamptz),
       (20, 'Partido Politico Cooperación Popular', 'Cooperación Popular es un partido político peruano de alcance nacional que se constituye en el marco de la Constitución Política del Perú y la legislación vigente sobre organizaciones políticas. El partido declara su respeto al Estado de Derecho, la democracia y las libertades fundamentales reconocidas constitucionalmente.

En términos ideológicos, el partido se posiciona en torno a la participación ciudadana, la autogestión comunitaria y la descentralización del poder político hacia la sociedad civil. Su orientación combina elementos de democracia participativa, desarrollo sostenible e inclusión social, sin adscribirse explícitamente a una corriente ideológica tradicional de izquierda o derecha.

Sus principios centrales incluyen la transparencia y la ética en la gestión pública, la equidad y la justicia social, el desarrollo sustentable, el acceso universal a educación y salud, el combate a la corrupción, el fortalecimiento de la participación ciudadana, la promoción de la diversidad e inclusión cultural y de género, y el impulso al desarrollo tecnológico y científico articulado con el sector académico y privado.

En cuanto a sus objetivos programáticos, el partido busca establecer mecanismos que amplíen la participación ciudadana en la toma de decisiones a nivel local y nacional, desarrollar programas de educación cívica para empoderar a la población, garantizar la transparencia y la rendición de cuentas de los representantes electos, promover un desarrollo económico equilibrado con criterios ambientales, e implementar políticas de igualdad de oportunidades para todos los ciudadanos independientemente de su origen étnico, género, orientación sexual o creencias. El partido se concibe a sí mismo como un puente entre las necesidades de las comunidades y las decisiones políticas, con especial énfasis en los centros poblados y entornos locales.',
        '2026-03-22 06:20:28.365496+00'::timestamptz),
       (21, 'Partido Politico Integridad Democrática', 'El Partido Político Integridad Democrática es una organización fundada en 2023 que se define a sí misma como una fuerza de centro, orientada a servir como punto de integración entre distintas posiciones ideológicas, con una visión humanista que sitúa la dignidad de la persona y el bien común como fundamentos de su acción política.

En términos ideológicos, el partido combina principios propios de la democracia cristiana y el liberalismo moderado. Defiende la economía social de mercado, que promueve la iniciativa privada y la libre competencia bajo un rol subsidiario del Estado, y al mismo tiempo reconoce la familia como núcleo básico de la sociedad, valora la solidaridad con los sectores más vulnerables y aboga por un Estado laico que respete la libertad religiosa. Su posicionamiento de centro se refleja en el equilibrio que busca entre la protección de derechos individuales y la responsabilidad colectiva.

Entre sus valores centrales destacan la transparencia, la meritocracia, la justicia, la equidad, el Estado de derecho y la participación ciudadana. El partido enfatiza la lucha contra la corrupción, el control riguroso del gasto público y la institucionalización de las organizaciones políticas mediante mecanismos internos democráticos.

Sus objetivos programáticos principales incluyen el fortalecimiento de las instituciones democráticas, la descentralización y el desarrollo regional sostenible, la modernización del Estado a través de la eficiencia y la meritocracia en la función pública, la promoción de la ciencia, tecnología e innovación como motores de competitividad nacional, la protección del medio ambiente, el respeto irrestricto a los derechos humanos y la generación de igualdad de oportunidades para todos los ciudadanos sin distinción de origen, género o condición social.',
        '2026-03-22 06:21:02.071863+00'::timestamptz),
       (22, 'Partido Politico Perú Acción', 'Partido Político Perú Acción es una organización política de alcance nacional que orienta su acción en torno a principios de democracia, Estado de Derecho, respeto irrestricto a los derechos humanos, solidaridad, justicia social, paz y desarrollo sostenible. Desde el punto de vista ideológico, el partido se inscribe en una posición de centro, combinando el compromiso con la economía social de mercado con la preocupación por el pago de la deuda social y la seguridad integral de la ciudadanía, sin adscribirse explícitamente a una corriente doctrinaria de izquierda o derecha.

Entre sus principales objetivos programáticos destacan la consolidación y defensa del sistema democrático, el fortalecimiento del Estado de Derecho, la reconstrucción moral del país, la preservación de las libertades individuales y la contribución a la gobernabilidad de la República. El partido también enfatiza la seguridad ciudadana y el cumplimiento de compromisos sociales pendientes con la población.

En cuanto a su organización interna, el partido exige a sus afiliados una conducta moral intachable, prohíbe la pertenencia simultánea a otras organizaciones políticas y excluye a personas condenadas por corrupción, narcotráfico, terrorismo u otros delitos graves. Cuenta con una Escuela Política orientada a la formación ideológica y cívica de sus miembros, y establece mecanismos de disciplina interna graduados según la gravedad de las faltas cometidas.',
        '2026-03-22 06:21:43.876132+00'::timestamptz),
       (23, 'Partido Politico Perú Libre', 'Perú Libre es un partido político peruano de orientación ideológica socialista, antiimperialista e internacionalista. Sus principios rectores incluyen el descentralismo, la democracia, la inclusión, la soberanía, el humanismo y el antiimperialismo. El partido se identifica con los sectores populares, incluyendo obreros, campesinos, estudiantes y empleados, y expresa solidaridad con organizaciones internacionales que comparten sus objetivos de socialismo, paz y justicia social.

En términos ideológicos, el partido se posiciona en la izquierda política, orientando su acción hacia la instauración del socialismo como sistema social, con énfasis en la eliminación de la explotación y la discriminación. Defiende la autodeterminación de los pueblos y la soberanía nacional frente a lo que considera injerencias imperialistas, y promueve la integración y unidad de los peruanos como base para el desarrollo colectivo.

Sus principales objetivos programáticos giran en torno a seis ejes considerados innegociables: el acceso a la educación y la erradicación del analfabetismo, la provisión de salud pública de calidad bajo un sistema unificado y solidario, la lucha contra la contaminación ambiental y la defensa de los recursos naturales, el combate a la corrupción, y la defensa de la soberanía nacional. El partido aspira a construir una sociedad equitativa e incluyente que garantice igualdad de oportunidades para todos los peruanos, con especial atención a los sectores históricamente desfavorecidos.',
        '2026-03-22 06:23:00.381971+00'::timestamptz),
       (24, 'Partido Politico Perú Primero', 'El Partido Político Perú Primero se define a partir de principios humanistas y democráticos, posicionándose como una organización de centro con orientación a la democracia representativa, el estado de derecho y la economía social de mercado. Considera a la familia como célula fundamental de la sociedad y rechaza explícitamente cualquier ideología extremista o totalitaria, tanto de origen nacional como extranjero.

Entre sus valores centrales se encuentran la ética, la libertad, la democracia, la transparencia y la independencia ideológica. El partido asume el servicio público como razón de ser de la acción política y promueve la participación ciudadana activa, incluyendo la de grupos históricamente subrepresentados como mujeres, jóvenes, comunidades nativas y campesinas, y poblaciones vulnerables.

En cuanto a sus objetivos programáticos, el partido busca fortalecer la institucionalidad democrática y el equilibrio de poderes, combatir la corrupción mediante la práctica de valores, e impulsar la descentralización y regionalización efectivas. En materia económica, apoya el desarrollo de pequeñas y medianas empresas como motores de empleo e innovación, y promueve el acceso a la propiedad como base del desarrollo individual. Asimismo, prioriza la mejora del acceso a la educación, la ciencia y la tecnología como pilares del desarrollo nacional, la igualdad de género en el acceso a instancias de gobierno, la protección social de poblaciones vulnerables y la construcción de una sociedad segura y justa. Su visión apunta a un Perú integrado al mundo, respetuoso de los derechos humanos y con estándares de desarrollo comparables a los de países de primer mundo.',
        '2026-03-22 06:24:46.540266+00'::timestamptz),
       (25, 'Partido SíCreo', 'El Partido Sicreo es una organización política peruana de carácter democrático que se fundamenta en la defensa de los derechos inherentes e inalienables de la persona humana, comenzando por el derecho a la vida y la libertad. Reconoce la dignidad humana y considera a la familia como institución fundamental de la sociedad. Entre sus principios jurídicos destaca la igualdad ante la ley, la presunción de inocencia, el debido proceso, el indubio pro reo, la irretroactividad de las leyes y el interés superior del niño. Asimismo, promueve la separación de poderes, los mecanismos de fiscalización y una justicia célere y eficaz.

Desde el punto de vista ideológico, el partido se ubica en una posición de centroderecha o derecha liberal, con un énfasis marcado en la libertad individual, la economía de libre mercado, el libre comercio y la propiedad privada. Rechaza explícitamente el totalitarismo en todas sus formas, incluyendo el comunismo, el nazismo y el fascismo, así como el colectivismo y el intervencionismo estatal en la economía y en la esfera privada. Defiende las libertades civiles clásicas, entre ellas la libertad de expresión, de prensa, de conciencia, de religión y de asociación.

Sus principales objetivos programáticos incluyen el fortalecimiento del Estado de derecho y la lucha frontal contra la corrupción y el crimen organizado. En materia económica, busca promover la inversión privada nacional y extranjera, reducir la informalidad mediante la simplificación administrativa y garantizar la seguridad jurídica y la estabilidad monetaria. En el ámbito social, impulsa el empoderamiento de la mujer, la protección de los derechos de la niñez, la inclusión de los adultos mayores, la participación juvenil y el fomento del voluntariado en alianza con el sector privado y la sociedad civil. En materia de gestión pública, promueve la meritocracia, la transparencia y la eliminación del clientelismo y el parasitismo burocrático, especialmente en los sectores de salud y educación.',
        '2026-03-22 06:25:36.306909+00'::timestamptz),
       (26, 'Partido de los Trabajadores y Emprendedores', 'El Partido de los Trabajadores y Emprendedores PTE-Perú es una organización política de alcance nacional que orienta su acción en torno a principios de paz, solidaridad, soberanía, cooperación, libertad, humildad y liderazgo. Su lema ''"Por igualdad, equidad y justicia social''" sintetiza una orientación ideológica de centro-izquierda con énfasis en el bienestar colectivo, la inclusión social y el desarrollo sostenible. El partido se autodefine como una fuerza orientada a refundar la república peruana en su etapa bicentenaria, buscando construir una nueva sociedad basada en la armonía, el desarrollo integral y la felicidad ciudadana.

Sus objetivos programáticos se articulan en torno a tres ejes: un país saludable, que incluye buena nutrición, atención médica preventiva y preservación del medio ambiente; un país pacífico, que promueve la educación orientada a la investigación, la eliminación de la violencia social, la erradicación de la corrupción y el fortalecimiento de la justicia; y un país sostenible, que fomenta la productividad a través de micro y pequeñas empresas, cooperativas y núcleos productivos, junto con la democracia participativa y la competitividad económica.

En cuanto a su estructura y funcionamiento interno, el partido establece mecanismos de democracia interna mediante elecciones con voto universal, libre, directo y secreto para la selección de autoridades y candidatos, con aplicación de criterios de paridad y alternancia en la conformación de listas. La afiliación es abierta a cualquier ciudadano sin distinción, y el régimen disciplinario contempla un Tribunal Nacional de Ética y Disciplina encargado de velar por la conducta de sus miembros, con especial énfasis en la protección de las mujeres frente al acoso en la vida política interna.',
        '2026-03-22 06:26:24.799465+00'::timestamptz),
       (27, 'Partido del Buen Gobierno', 'El Partido del Buen Gobierno (PBG) es una organización política peruana de alcance nacional que se define a sí misma como una comunidad ciudadana fundamentada en la integridad ética y el compromiso con la transformación del país. Su eslogan es ''"Gobernar es Unir''" y su símbolo remite a la iconografía andina, concretamente a una figura solar inspirada en los dibujos de Felipe Guamán Poma de Ayala.

En cuanto a sus principios y valores, el partido combina el reconocimiento de la herencia civilizatoria andina, amazónica, afroperuana e hispanoárabe con una orientación hacia la modernización institucional. Promueve la conciencia ambiental ante la crisis climática, el respeto irrestricto a los derechos humanos, la laicidad del Estado, la diversidad de pensamiento y el rechazo a cualquier dogmatismo ideológico. Enfatiza la transparencia, la participación ciudadana activa, la igualdad, la libertad y la solidaridad como ejes de su acción política. También destaca el diálogo intergeneracional y la inclusión de jóvenes, mujeres y líderes comunitarios como actores centrales del cambio.

Ideológicamente, el partido se ubica en el centro reformador y transformador del espectro político, rechazando explícitamente posiciones extremas y declarando no suscribir ningún pensamiento único. Se apoya en el análisis racional basado en hechos y evidencias, y reivindica una visión utópica de la democracia como horizonte político.

Sus principales objetivos programáticos apuntan a la construcción de un Estado ciudadano que responda integralmente a las necesidades de la población, con especial atención a los grupos vulnerables. Busca impulsar una reforma institucional profunda que promueva la transparencia y la gobernabilidad mediante consensos entre fuerzas políticas y sociedad civil. Propone desarrollar una economía de competencia e innovación orientada al desarrollo sostenible y sustentable, vigilar el uso de los fondos públicos, fortalecer la formación cívica de la ciudadanía y garantizar la vigencia de los derechos fundamentales conforme a la Constitución peruana y los tratados internacionales. El partido concibe el acceso al poder no como un fin en sí mismo, sino como instrumento para implementar los cambios que considera urgentes para el bienestar de todos los peruanos.',
        '2026-03-22 06:26:56.997223+00'::timestamptz),
       (28, 'Perú Moderno', 'Perú Moderno es un partido político peruano de carácter democrático e independiente, cuya orientación ideológica puede describirse como de centro a centro-izquierda, con énfasis en la justicia social, el desarrollo productivo y la modernización del Estado. Sus principios fundacionales incluyen el respeto a la dignidad humana y los derechos de las personas, el reconocimiento del trabajo como factor central del desarrollo económico y social, la justicia social como objetivo de gobierno, el ejercicio ético de la política, la democracia con igualdad de oportunidades, y la soberanía nacional con uso racional de los recursos naturales.

En cuanto a su visión programática, el partido propone una transformación estructural del país orientada a alcanzar estándares de desarrollo de primer mundo. Para ello, plantea redefinir la relación entre el Estado, el mercado y la comunidad científica, promoviendo un mercado interno productivo con incorporación de tecnología, un Estado promotor, descentralizado, transparente y libre de corrupción, así como la integración sudamericana y la cooperación multilateral en favor de la paz y el desarrollo sostenible. También enfatiza la inclusión social, la identidad nacional y la eliminación de la criminalidad organizada como condiciones para el progreso.

Organizativamente, el partido adopta una estructura democrática interna con mecanismos de participación de afiliados, procesos electorales internos y un sistema de disciplina partidaria a través de tribunales de ética de alcance regional y nacional. La membresía está abierta a ciudadanos mayores de dieciocho años sin distinción de sexo, credo, cultura o condición social, y el financiamiento se sustenta en aportes de afiliados, contribuciones de autoridades elegidas y fondos públicos correspondientes a organizaciones políticas.',
        '2026-03-22 06:27:46.047595+00'::timestamptz),
       (29, 'Podemos Perú', 'Podemos Perú es un partido político de alcance nacional constituido conforme a la Constitución Política del Perú y la Ley de Organizaciones Políticas. Su estatuto remite a un Ideario para la definición explícita de sus principios, aunque a lo largo del documento se identifican valores transversales como la democracia, el Estado de Derecho, la paz, la libertad, la honestidad, la vocación de servicio social y el amor a la patria. En términos ideológicos, el partido no se adscribe explícitamente a una corriente específica del espectro político, presentándose como una organización de orientación democrática y centrada en la gobernabilidad y el desarrollo nacional.

Sus principales objetivos programáticos incluyen la defensa y consolidación del sistema democrático y del Estado de Derecho, la preservación de la paz y la libertad, la promoción de políticas educativas orientadas al desarrollo del país, la participación en procesos electorales y consultas ciudadanas, la contribución a la gobernabilidad de la República, y la realización de actividades de cooperación y proyección social.

En cuanto a su organización interna, el partido establece mecanismos de afiliación voluntaria con requisitos que incluyen la ciudadanía peruana habilitada y la ausencia de condenas por delitos graves como corrupción, narcotráfico o terrorismo. Dispone de un sistema disciplinario graduado en faltas leves, graves y muy graves, con sanciones que van desde la amonestación escrita hasta la expulsión, garantizando el debido proceso y la doble instancia. El partido reconoce derechos y deberes a sus afiliados, entre ellos la participación en procesos de democracia interna, la fiscalización ética de los funcionarios electos bajo sus candidaturas y la contribución económica al sostenimiento de la organización.',
        '2026-03-22 06:28:21.465732+00'::timestamptz),
       (30, 'Primero la Gente', 'El partido político Primero la Gente - Comunidad, Ecología, Libertad y Progreso es una organización peruana que articula su identidad en torno a cuatro ejes centrales sintetizados en su lema: comunidad, ecología, libertad y progreso. Sus principios fundacionales incluyen la democracia de base, la participación ciudadana, el pluralismo político, los liderazgos múltiples y la dignidad de la persona como fundamento del sistema democrático.

Desde el punto de vista ideológico, el partido presenta un perfil de centro-izquierda con marcada orientación ecologista y progresista. Combina elementos del comunitarismo, el desarrollo sostenible y la justicia social con la defensa de libertades individuales, el estado de derecho y una economía social de mercado. Se identifica con principios del Buen Vivir en relación con los pueblos originarios, y adhiere a los Objetivos de Desarrollo Sostenible de las Naciones Unidas.

Entre sus principales objetivos programáticos destacan la protección del medio ambiente y la diversidad ecológica, la promoción de energías renovables y ciudades sostenibles, la defensa de los derechos de comunidades indígenas, campesinas y poblaciones afrodescendientes, y la lucha contra toda forma de discriminación. En materia económica, promueve la pequeña y microempresa, la soberanía alimentaria, la inversión en infraestructura y la planificación sostenible de industrias extractivas. En el ámbito social, impulsa la inclusión, la igualdad de género, el acceso universal a salud, educación y trabajo digno, así como la reforma del Estado mediante meritocracia, transparencia y lucha contra la corrupción. En política exterior, apoya la integración andina y latinoamericana y la cooperación internacional.',
        '2026-03-22 06:29:00.002012+00'::timestamptz),
       (31, 'Progresemos', 'Progresemos es una organización política peruana cuya base ideológica se sustenta en el humanismo, entendido como el amor y respeto hacia todo ser viviente, incluyendo animales y el medio ambiente. Sus principios rectores son la ética, la democracia representativa, la libertad individual, la independencia frente a ideologías extremistas o totalitarias, y la transparencia en su gestión financiera. El partido se posiciona en un centro democrático, sin adscripción a corrientes ideológicas de izquierda o derecha definidas, rechazando explícitamente los extremismos y priorizando la inclusión social y el bien común.

Entre sus principales objetivos programáticos se encuentran la promoción de la participación política equitativa de hombres, mujeres, comunidades nativas, jóvenes y poblaciones vulnerables; el impulso a la educación, la ciencia y la tecnología como pilares del desarrollo sostenible; el apoyo a las pequeñas y medianas empresas y a los sectores productivos agrícolas y pesqueros artesanales históricamente desatendidos; y la descentralización de los servicios públicos. Asimismo, el partido enfatiza la lucha contra la corrupción desde la formación en valores en el ámbito familiar y educativo, la igualdad de género, la atención a personas con discapacidad y adultos mayores, la protección animal y medioambiental, y la reforma del marco normativo en materia de seguridad y justicia para hacerlo más efectivo frente a la realidad del país.',
        '2026-03-22 06:29:54.962553+00'::timestamptz),
       (32, 'Renovación Popular', 'Renovación Popular es un partido político peruano de orientación humanista cristiana, cuya acción política se fundamenta en la promoción del desarrollo integral de la persona y la familia como ejes centrales, articulados en torno al bien común del pueblo peruano. Sus principios rectores son la libertad, la igualdad, la justicia y la solidaridad, enmarcados dentro de una concepción democrática representativa y participativa con enfoque descentralista.

Ideológicamente, el partido se posiciona en una línea democrática de centro con raíces en el humanismo cristiano, comprometido con el respeto irrestricto a la seguridad jurídica, a las libertades fundamentales y a los derechos consagrados en la Constitución Política del Perú. Rechaza expresamente conductas antidemocráticas y reñidas con la ética tanto en sus militantes como en sus candidatos.

Entre sus principales objetivos programáticos se encuentran la búsqueda del bien común como fin político superior, el fortalecimiento de la institucionalidad democrática, la promoción de una carrera política basada en méritos éticos y trayectoria, y la descentralización del Estado. El partido enfatiza la formación política y técnica permanente de sus afiliados, así como la transparencia en el manejo de sus finanzas, estableciendo mecanismos de control contable y rendición de cuentas ante los organismos electorales competentes. La participación ciudadana es valorada tanto a través de la afiliación formal como mediante la figura de adherentes que colaboran con la organización sin vinculación partidaria plena.',
        '2026-03-22 06:30:35.099709+00'::timestamptz),
       (33, 'Salvemos al Perú', 'Salvemos al Perú es un partido político peruano de orientación centrista y progresista, fundado sobre los ejes ideológicos de la libertad individual, la dignidad de la persona y el fortalecimiento de la familia como núcleo fundamental de la sociedad. Su postura ideológica combina la defensa de la economía social de mercado y la libre empresa con un énfasis en la equidad social, el desarrollo humano y la igualdad de oportunidades para todos los ciudadanos.

Entre sus principios centrales destacan el respeto a las libertades individuales, la promoción de la democracia representativa, la separación e independencia de poderes, y el rechazo a cualquier forma de imposición ideológica. El partido se declara firmemente comprometido con la lucha contra la corrupción, el narcotráfico, la delincuencia y el crimen organizado, identificándolos como los principales obstáculos para el desarrollo nacional. Asimismo, promueve el diálogo, la negociación y el consenso como mecanismos de participación política, y rechaza explícitamente toda forma de violencia contra la mujer.

En términos programáticos, el partido tiene como objetivos principales la generación de riqueza y empleo digno, la mejora de los sistemas de educación, salud y seguridad ciudadana, y la modernización del Estado para ponerlo al servicio del ciudadano. Propone una reforma profunda del sistema judicial y del Ministerio Público, la descentralización del desarrollo económico y social hacia las regiones, y la promoción de la identidad e integración nacional sin distinción de etnia, lengua, género, religión ni condición socioeconómica. El partido también reconoce los desafíos que plantea la transformación tecnológica global, incluyendo la automatización y la robótica, como factores que requieren una planificación estatal anticipada orientada al bienestar común.',
        '2026-03-22 06:31:10.884155+00'::timestamptz),
       (34, 'Un Camino Diferente', '''"Un Camino Diferente''" es un partido político peruano fundado el 1 de enero de 2024, con sede en la ciudad de Trujillo, departamento de La Libertad. Se define ideológicamente como un partido de centro, inspirado en los principios fundamentales de la democracia: igualdad, libertad, estado de derecho, solidaridad y respeto a los derechos humanos. Su simbolismo institucional recurre a referentes de las culturas precolombinas andinas, incorporando figuras de la tradición Mochica e Inca como elementos de identidad visual.

En cuanto a su estructura organizativa, el partido se articula en torno a un Congreso Nacional como órgano supremo, un Comité Ejecutivo Nacional como instancia máxima de dirección ejecutiva, y una Presidencia como órgano principal de representación y conducción política. Complementan esta estructura los comités provinciales y distritales, así como un Tribunal de Ética y Disciplina y un Tribunal Electoral Nacional. La figura de Presidente Fundador, de carácter honorífico y vitalicio, recae en su fundadora, Rocío del Pilar Fernández Bazán.

Desde el punto de vista programático, el partido orienta su acción hacia la consolidación del sistema democrático, la participación política ciudadana y el funcionamiento institucional ordenado conforme al marco legal peruano, particularmente la Ley de Organizaciones Políticas. Sus objetivos centrales incluyen la definición de lineamientos de gobierno a largo plazo, la selección democrática de candidatos a cargos de elección popular y la construcción de una organización política territorialmente articulada a nivel nacional.',
        '2026-03-22 06:32:00.512097+00'::timestamptz),
       (35, 'Unidad Nacional', 'El Partido Popular Cristiano (PPC) es una organización política peruana fundada el 18 de diciembre de 1966, que se define ideológicamente como un partido socialcristiano, sustentado en los valores del humanismo cristiano y comprometido con el fortalecimiento de la democracia. Su acción política se orienta a la promoción del desarrollo integral de la persona humana y la familia como ejes centrales, así como a la consecución del bien común del pueblo peruano.

Los principios fundamentales que guían al partido son la libertad, la igualdad, la justicia y la solidaridad. En consonancia con su orientación doctrinal, promueve la Doctrina Social Cristiana y la Economía Social de Mercado como marcos de referencia para sus propuestas programáticas y la formación de sus militantes. El humanismo cristiano constituye la base filosófica de su concepción política, colocando a la persona humana en el centro de toda actuación pública y privada.

En cuanto a su estructura y funcionamiento interno, el partido fomenta la participación activa de sus afiliados en los procesos de toma de decisiones, garantiza su derecho a elegir y ser elegidos para cargos directivos o de elección popular, y promueve la carrera partidaria como mecanismo de ascenso gradual a mayores responsabilidades. Exige de sus militantes lealtad a los principios doctrinarios, conducta ética, capacitación permanente y participación en las actividades del partido. Los representantes con funciones públicas deben actuar en coherencia con la línea política del partido, conservando autonomía en decisiones de carácter técnico y administrativo.

El partido mantiene vinculación con organizaciones internacionales afines al pensamiento socialcristiano y promueve la interacción de sus dirigentes con gremios profesionales, organizaciones sociales, empresariales y sindicales, en cumplimiento de su rol de intermediación entre la sociedad y el Estado. Su financiamiento proviene de aportes de afiliados, donaciones, subvenciones y otros recursos legalmente permitidos.',
        '2026-03-22 06:32:37.068839+00'::timestamptz),
       (36, 'Venceremos', 'Nuevo Perú por el Buen Vivir es una organización política peruana de izquierda que se define como democrática, descentralizada, plural, ciudadana y popular. Su identidad ideológica se articula desde una posición crítica al neoliberalismo, al capitalismo, al imperialismo, al colonialismo y al patriarcado, recogiendo diversas tradiciones políticas y culturales progresistas. El partido asume un enfoque pluricultural e internacionalista, comprometido con la soberanía nacional, la autodeterminación de los pueblos y los derechos humanos, en el marco de un mundo multipolar con integración solidaria entre naciones.

Sus principios organizativos giran en torno a la democracia interna participativa, representativa y directa, la transparencia en la gestión de recursos y la toma de decisiones, la ética institucional, y el respeto a la diversidad de pensamiento. La organización promueve la participación activa de la militancia y la ciudadanía, con énfasis en la inclusión de mujeres, jóvenes, pueblos indígenas, comunidades afrodescendientes y la comunidad LGTBIQ+, aplicando criterios de paridad y alternancia en sus estructuras internas.

En términos programáticos, el partido busca construir un proyecto de transformación estructural del Perú orientado hacia la soberanía popular, la democratización radical del Estado, la descentralización del poder y el reconocimiento de la pluriculturalidad. Aspira a constituir un sujeto político colectivo que articule a trabajadores, sectores populares y grupos históricamente excluidos en torno a un proyecto constituyente y de poder ciudadano. La organización también establece mecanismos específicos para prevenir el acoso político contra las mujeres y garantizar condiciones equitativas de participación política interna.',
        '2026-03-22 06:35:47.957452+00'::timestamptz)
ON CONFLICT (id) DO UPDATE SET name       = EXCLUDED.name,
                               summary    = EXCLUDED.summary,
                               created_at = EXCLUDED.created_at;

SELECT setval(pg_get_serial_sequence('parties', 'id'), COALESCE((SELECT MAX(id) FROM parties), 1));
